2025-06-01 12:11:46,810 INFO    MainThread:7653 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-06-01 12:11:46,810 INFO    MainThread:7653 [wandb_setup.py:_flush():67] Configure stats pid to 7653
2025-06-01 12:11:46,810 INFO    MainThread:7653 [wandb_setup.py:_flush():67] Loading settings from /Users/heshuhua/.config/wandb/settings
2025-06-01 12:11:46,810 INFO    MainThread:7653 [wandb_setup.py:_flush():67] Loading settings from /Users/heshuhua/lab/ailab/llmlab/trainlab/wandb/settings
2025-06-01 12:11:46,810 INFO    MainThread:7653 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-06-01 12:11:46,810 INFO    MainThread:7653 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /Users/heshuhua/lab/ailab/llmlab/trainlab/wandb/run-20250601_121146-lnox82v7/logs/debug.log
2025-06-01 12:11:46,810 INFO    MainThread:7653 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /Users/heshuhua/lab/ailab/llmlab/trainlab/wandb/run-20250601_121146-lnox82v7/logs/debug-internal.log
2025-06-01 12:11:46,810 INFO    MainThread:7653 [wandb_init.py:init():781] calling init triggers
2025-06-01 12:11:46,810 INFO    MainThread:7653 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-06-01 12:11:46,810 INFO    MainThread:7653 [wandb_init.py:init():809] starting backend
2025-06-01 12:11:46,810 INFO    MainThread:7653 [wandb_init.py:init():813] sending inform_init request
2025-06-01 12:11:46,896 INFO    MainThread:7653 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-06-01 12:11:46,896 INFO    MainThread:7653 [wandb_init.py:init():823] backend started and connected
2025-06-01 12:11:46,900 INFO    MainThread:7653 [wandb_init.py:init():915] updated telemetry
2025-06-01 12:11:46,988 INFO    MainThread:7653 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-06-01 12:12:16,616 WARNING MainThread:7653 [wandb_init.py:init():1534] [no run ID] interrupted
Traceback (most recent call last):
  File "/opt/anaconda3/envs/dgai/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1530, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/dgai/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 965, in init
    result = wait_with_progress(
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/dgai/lib/python3.12/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 24, in wait_with_progress
    return wait_all_with_progress(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/dgai/lib/python3.12/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 87, in wait_all_with_progress
    return asyncio_compat.run(progress_loop_with_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/dgai/lib/python3.12/site-packages/wandb/sdk/lib/asyncio_compat.py", line 30, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/dgai/lib/python3.12/concurrent/futures/_base.py", line 451, in result
    self._condition.wait(timeout)
  File "/opt/anaconda3/envs/dgai/lib/python3.12/threading.py", line 355, in wait
    waiter.acquire()
KeyboardInterrupt
2025-06-01 12:12:17,213 INFO    MsgRouterThr:7653 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
